function [b] = qfir( Fs )
%FIR Returns a discrete-time filter object.

%
% MATLAB Code
% Generated by MATLAB(R) 7.14 and the Signal Processing Toolbox 6.17.
%
% Generated on: 27-Nov-2015 09:48:30
%

% FIR Window Bandpass filter designed using the FIR1 function.

% All frequency values are in GHz.
%Fs = 44;  % Sampling Frequency
Fs=Fs/10^9;
N    = 50;       % Order
Fc1  = 5.65;     % First Cutoff Frequency
Fc2  = 7.95;     % Second Cutoff Frequency
flag = 'scale';  % Sampling Flag
% Create the window vector for the design algorithm.
win = hamming(N+1);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, [Fc1 Fc2]/(Fs/2), 'bandpass', win, flag);
Hd = dfilt.dffir(b);

% [EOF]
